### ISSUE TITLE
details 

### ISSUE THREAD

**Issue by 3073** [PJunhyuk/people-counting-classification#3]
Hi it is a great repo. 
could you detail how to use it? 
What is the specific type of detector used?
Explain me each line of code so that I can donate for your explanation. 

Thank you

**Comment by 3073** [comment]
ModuleNotFoundError: No module named 'nms_grid'

how do i fix it
 thank you

**Comment by PJunhyuk** [comment]
Sorry for late. Thanks for your interest!

For detector,
In video_tracking.py, I used correlation_tracker in dlib. For multi target tracking.
In video_tracking_sort.py, I used [SORT tracker- Simple, online, and realtime tracking of multiple objects in a video sequence](https://github.com/abewley/sort), but it is not complete.

For nms_grid,
These codes are built for linux. So if you use windows, it won't run fine. I have plan to build it for windows.
Please check [issue 26 in eldar/pose-tensorflow](https://github.com/eldar/pose-tensorflow/issues/26)

**Comment by 3073** [comment]
I am glad you respond me and thank you for that.


what is the type of detector besides the pose estimator? because i am
seeing a bounding boxes over the objects.

**Comment by PJunhyuk** [comment]
First, this model finds pose of human by using pose estimation algorithm, based on [pose-tensorflow](https://github.com/eldar/pose-tensorflow). Then, it draws bounding box which include all points of human. In detail, each corners of bounding box are min&max value of 17 point that detected by pose estimation algorithm.
And we put that bounding boxes to detector, correlation_tracker.

**Comment by 3073** [comment]
I need to use it in raspberry pi so that it can run in real time. is there
a possibility for that and if it is possible which things should change?

Thank you for real

**Comment by PJunhyuk** [comment]
This code is hard to run in real time, because it does not use the GPU.
When I tested this code in CPU Intel(r) Xeon(R) CPU E5-2687W v3 @ 3.10GHz, it takes 140.0sec for test_video_01.mov (2.0MB, 72 frame, [1280, 720])
If you want to run pose-estimation in real time, maybe you can check [openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose).

**Comment by 3073** [comment]
Thank you
