### ISSUE TITLE
counting part

### ISSUE THREAD

**Issue by 3073** [PJunhyuk/people-counting-classification#4]
I was using the counting part in video_tracking.py in line 217, 218, 219.
but the problem is if for instance there are 2 people in  the first frame it output a cumulative of 2. then if 3 people are entered the next frame, it output 3 which it should be 5. sorry if I mistaken something. 

if tracker_len_prev < int(len(tracker)):
        tracking_people_count = tracking_people_count + int(len(tracker)) - tracker_len_prev
tracker_len_prev = int(len(tracker))

**Comment by PJunhyuk** [comment]
In your case,

after frame1
len(tracker) = 2
tracking_people_count = 2
tracker_len_prev = 2

for frame2
tracker_len_prev = 2 in line 217
len(tracker) = 5 in line 217
tracking_people_count = 2 + 5 - 2 = 5 in line 218
tracker_len_prev = 5 in line 219 (update)

I hope it helps your understanding :)

**Comment by 3073** [comment]
thanks a lot for real 

if I catch you, your saying is "len(tracker) is equal to the number of objects( people) tracked in the previous frames plus the current frame"  and tracking_people_count  is always equal to tracker_len_prev.

       if that is so this is my final understanding!!!
since a person once tracked is not tracked again it will not be counted twice or three times even if  it appears in successive frames.
I am Right?
One more question. 
this code do not run  on windows. can I run it if   I install  Ubuntu along side windows 7 ( dual boot)?

thanks that  you are not tired to answer me!!!

**Comment by PJunhyuk** [comment]
This code does not run on windows, so if you want to run it on windows, you have to use [docker toolbox](https://docs.docker.com/toolbox/toolbox_install_windows/).

**Comment by 3073** [comment]
one more thing please!!!
 can you please tell me some details  how to run it on docker for windows OS?
thanks

**Comment by PJunhyuk** [comment]
@3073 Maybe you can just check [Install Docker Toolbox on Windows](https://docs.docker.com/toolbox/toolbox_install_windows/) page!
On Docker terminal, you can follow steps in README file in this repo :)

**Comment by 3073** [comment]
ok I will  give a try and tell you the result.

**Comment by 3073** [comment]
Hi there
I have assembled the SSD detectors with kalman tracker and I take the
counting part from your source code to count them as you have did in this
great repo. but the problem is counting is total number. it does not
identify the direction the person goes.   is there a way to add that(
consider the direction of travel like the case enter and exit of objects
form an area )

Thank you
