### ISSUE TITLE
Can this work for real-time stream? Like CCTV

### ISSUE THREAD

**Issue by staymillion** [PJunhyuk/people-counting-classification#8]
If it can work in real-time video and show result directly on a video seems more awesome

**Comment by PJunhyuk** [comment]
This code is hard to run in real time, because it does not use the GPU.
When I tested this code in CPU Intel(r) Xeon(R) CPU E5-2687W v3 @ 3.10GHz, it takes 140.0sec for test_video_01.mov (2.0MB, 72 frame, [1280, 720])
If you want to run pose-estimation in real time, maybe you can check openpose.
