### ISSUE TITLE
Illegal instruction (core dumped) when importing moviepy

### ISSUE THREAD

**Issue by wnasich** [PJunhyuk/people-counting-classification#9]
I pulled the docker image on Ubutnu 17.10 x86_64. I get this message when `moviepy.edit` is imported:
Illegal instruction (core dumped)

https://github.com/PJunhyuk/people-counting-pose/blob/1ecfddd2045963f24c4d4e49bb3dc37223ef83ff/video_tracking.py#L13

Are there some log file that I should provide?

**Comment by PJunhyuk** [comment]
I think it is occurred by moviepy itself. You have to check its official website (https://zulko.github.io/moviepy/)
